/**
 * Video routes — the personalized phonics song.
 *
 *  POST /api/videos             compile + queue this child's next song
 *  GET  /api/videos/:id/status  poll a render (state, progress)
 *  GET  /api/videos/:id/file    stream the finished mp4
 *  GET  /api/videos/child/:id   this child's songs, newest first
 *
 * Security shape matches the story routes exactly: parent session on every
 * route, child ownership re-proven before anything child-scoped, Zod on every
 * input. Nothing here is generated by a model — the script is compiled from
 * the phonics scope, so no prompt can be steered and there is no generated
 * prose to moderate.
 */
import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import type { LearnerModel, WorldSeed } from '@qissa/core';
import { z } from 'zod';
import type { FastifyInstance } from 'fastify';
import { ctx } from '../context.js';
import { audit } from '../safety/audit.js';
import {
  adoptExisting,
  enqueueRender,
  existingVideo,
  getJob,
  jobsForChild,
  videoPath,
  type VideoJob
} from '../video/jobs.js';
import { assembleSong, scriptForChild, scriptTitle } from '../video/song.js';
import { denyNotFound, ownedChild, requireAuth } from './guards.js';
import { parseBody, parseParams } from './validate.js';

const CreateSchema = z.object({ childId: z.string().min(1).max(64) }).strict();
/** Job ids are hex digests this server minted; pin the shape so an id that
 *  could never have been minted here is rejected before any disk access. */
const JobIdParams = z.object({ id: z.string().regex(/^[0-9a-f]{32}$/) }).strict();
const ChildIdParams = z.object({ id: z.string().min(1).max(64) }).strict();

/** What a parent sees — never a file path, never a vendor error. */
function publicJob(job: VideoJob): Record<string, unknown> {
  return {
    id: job.id,
    title: job.title,
    state: job.state,
    progress: Math.round(job.progress * 100) / 100,
    error: job.error,
    renderMs: job.renderMs
  };
}

/**
 * The id for a video, derived from its content.
 *
 * A hash of the resolved props means an unchanged child asking twice maps to
 * the same id and therefore the same file — "watch it again" is instant, and a
 * double tap cannot start two renders. It also means advancing a sound
 * naturally produces a NEW video rather than overwriting the one the parent
 * just saved.
 */
function videoIdFor(childId: string, props: unknown): string {
  return createHash('sha256').update(childId).update(JSON.stringify(props)).digest('hex').slice(0, 32);
}

export async function videoRoutes(app: FastifyInstance): Promise<void> {
  const { prisma, providers, env } = ctx(app);

  app.post('/', { preHandler: requireAuth(app) }, async (request, reply) => {
    const body = parseBody(CreateSchema, request.body, reply);
    if (body === null) return;

    const child = await ownedChild(prisma, body.childId, request.auth.parent.id);
    if (child === null) return denyNotFound(reply);

    const learner = await prisma.learnerModel.findUnique({ where: { childId: child.id } });
    if (learner === null) return denyNotFound(reply);

    const worldSeed = child.worldSeed as unknown as WorldSeed;
    const script = scriptForChild(learner.state as unknown as LearnerModel, worldSeed);
    const title = scriptTitle(script);

    // Assembling narration and art happens before the id is known, because the
    // id is a hash of the RESOLVED props — the durations are part of what makes
    // two videos the same video. Both pieces are disk-cached, so the repeat
    // case costs a few file reads rather than a vendor call.
    const props = await assembleSong({ script, worldSeed, providers });
    const id = videoIdFor(child.id, props);

    if (await existingVideo(id)) {
      await audit(prisma, {
        event: 'video.reused',
        childId: child.id,
        detail: { videoId: id, grapheme: script.targetGrapheme }
      });
      return { video: publicJob(adoptExisting(id, child.id, title)) };
    }

    const job = enqueueRender({
      id,
      childId: child.id,
      title,
      props,
      log: request.log,
      concurrency: env.VIDEO_RENDER_CONCURRENCY
    });

    await audit(prisma, {
      event: 'video.queued',
      childId: child.id,
      detail: {
        videoId: id,
        grapheme: script.targetGrapheme,
        reviewGraphemes: script.reviewGraphemes,
        words: script.words,
        scriptVersion: script.version,
        scenes: props.scenes.length,
        // Which scenes lost an asset, so a poor video is diagnosable from the
        // audit log rather than by watching it. Discarding this is what cost
        // two diagnostic cycles on the story art.
        silentScenes: props.scenes.filter((s) => s.audioSrc === null).map((s) => s.id),
        // "Wanted a picture and did not get one" — decided from the SCRIPT,
        // which records whether art was requested, not from the presence of a
        // word. Inferring it from the word reported the blend scene as undrawn
        // on every single video: it shows a word and deliberately has no
        // picture. A diagnostic that always fires teaches you to ignore it.
        undrawnScenes: script.scenes
          .filter((s) => s.art !== undefined)
          .filter((s) => props.scenes.find((p) => p.id === s.id)?.imageSrc == null)
          .map((s) => s.id)
      }
    });

    return reply.code(202).send({ video: publicJob(job) });
  });

  app.get('/:id/status', { preHandler: requireAuth(app) }, async (request, reply) => {
    const params = parseParams(JobIdParams, request.params, reply);
    if (params === null) return;

    const job = getJob(params.id);
    if (job === undefined) return denyNotFound(reply);

    // Ownership is re-proven on the STATUS route too, not just at creation:
    // a job id is guessable in principle, and progress on another family's
    // render is still another family's information.
    const child = await ownedChild(prisma, job.childId, request.auth.parent.id);
    if (child === null) return denyNotFound(reply);

    return { video: publicJob(job) };
  });

  app.get('/child/:id', { preHandler: requireAuth(app) }, async (request, reply) => {
    const params = parseParams(ChildIdParams, request.params, reply);
    if (params === null) return;

    const child = await ownedChild(prisma, params.id, request.auth.parent.id);
    if (child === null) return denyNotFound(reply);

    return { videos: jobsForChild(child.id).map(publicJob) };
  });

  app.get('/:id/file', { preHandler: requireAuth(app) }, async (request, reply) => {
    const params = parseParams(JobIdParams, request.params, reply);
    if (params === null) return;

    const job = getJob(params.id);
    if (job === undefined || job.state !== 'ready') return denyNotFound(reply);

    const child = await ownedChild(prisma, job.childId, request.auth.parent.id);
    if (child === null) return denyNotFound(reply);

    const filePath = videoPath(job.id);
    try {
      const info = await stat(filePath);
      // Streamed, not read into memory: a 90-second 1080p song is tens of
      // megabytes, and buffering one per concurrent viewer is how a small
      // container runs out of heap.
      return reply
        .type('video/mp4')
        .header('content-length', String(info.size))
        .header('content-disposition', `inline; filename="qissa-${job.id}.mp4"`)
        .send(createReadStream(filePath));
    } catch {
      return denyNotFound(reply);
    }
  });
}
